### ISSUE TITLE
LoadGCS malfunctioning

### ISSUE THREAD

**Issue by sw1v3l** [WIGGLES-dev/GURPSFoundrySystem#1]
Hey, so I tried out your system today.  Manifest URL works great.  GCS import seems to be broken.  I'm running linux (shouldn't matter since it's JS).

I can choose a file to import, but there's no button to actually complete the import.
![image](https://user-images.githubusercontent.com/12145111/92995116-b9773f00-f4d6-11ea-9bde-5ff5f3a39c25.png)

Also, I checked the developer tools, and it seems to throw the same error after every attempt: 
![image](https://user-images.githubusercontent.com/12145111/92995127-d3188680-f4d6-11ea-97d2-01f9d709c188.png)

I also brought up that line in index.js to narrow it down for you: 
![image](https://user-images.githubusercontent.com/12145111/92995132-f5120900-f4d6-11ea-9a49-4e274d3fd98f.png)

**Comment by WIGGLES-dev** [comment]
closing this issue, it should be fixed in 1.2.2
