### ISSUE TITLE
Unable to delete items

### ISSUE THREAD

**Issue by Ethanrat** [WIGGLES-dev/GURPSFoundrySystem#2]
I am having a issue after updating to version 1.2.1 that is preventing me from deleting items in the items menu. I am currently using Foundry version 0.6.6 and have verified the issue is not present in any other installed systems.

**Comment by WIGGLES-dev** [comment]
Could you give me steps to reproduce your issue, as it appears to be working on chrome for me.

**Comment by Ethanrat** [comment]
I tried it on both Chrome and Firefox and still had the issue. Any new item I create or old ones that existed before the update are unable to be deleted. If I place the item in a folder then delete the folder there are no issues with removal. I can delete objects from all other tabs without issues. As far as steps to reproduce, I am just creating a Item on the item tab via the  Create Item button, any item I have previously created this way is unable to be deleted via the right click menu delete button.

**Comment by TheMook** [comment]
Can confirm the same issue and workaround (right-click to delete does not, moving item to a folder and deleting all contents does).
Foundry 0.6.6
GURPS 4E 1.2.1
Chrome 85.0.4183.102

**Comment by sw1v3l** [comment]
I can also confirm this issue.  

Error in console:
![image](https://user-images.githubusercontent.com/12145111/93025753-1d812c80-f5d7-11ea-9a4c-ae60e0c94196.png)

**Comment by WIGGLES-dev** [comment]
closing the issue, they should be fixed in 1.2.2
